name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.2.1'

    - name: Debug Gradle Wrapper
      run: |
        echo "Checking gradle wrapper files..."
        ls -la gradle/wrapper/
        echo "Gradle wrapper jar size:"
        ls -lh gradle/wrapper/gradle-wrapper.jar
        echo "Java version:"
        java -version
        echo "JAVA_HOME: $JAVA_HOME"

    - name: Build Debug APK
      run: |
        if [ -f "./gradlew" ] && [ -f "gradle/wrapper/gradle-wrapper.jar" ]; then
          ./gradlew assembleDebug --stacktrace --info
        else
          gradle assembleDebug --stacktrace --info
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
