name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# 👇 Permessi per consentire push da parte di github-actions[bot]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Cache Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle*','**/*.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Rendi eseguibile il wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Build APK (debug)
      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      # (Opzionale) Commit nuovo wrapper se rigenerato
      - name: Commit new wrapper (if changed)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if git diff --quiet gradle/wrapper/; then
            echo "No changes to wrapper"
          else
            echo "Committing new wrapper..."
            git add gradle/wrapper/
            git commit -m "Auto-fix: Regenerate gradle wrapper [skip ci]"
            git push
          fi
