name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.2.1'

    - name: Remove old wrapper and regenerate with correct version
      run: |
        echo "Removing potentially corrupted wrapper..."
        rm -f gradle/wrapper/gradle-wrapper.jar
        echo "Regenerating Gradle Wrapper with version 8.2.1..."
        gradle wrapper --gradle-version 8.2.1 --distribution-type bin
        chmod +x ./gradlew
        echo "Wrapper regenerated successfully!"

    - name: Verify wrapper works
      run: ./gradlew --version

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk

    - name: Commit new wrapper (if changed)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if git diff --quiet gradle/wrapper/; then
          echo "No changes to wrapper"
        else
          echo "Committing new wrapper..."
          git add gradle/wrapper/
          git commit -m "Auto-fix: Regenerate gradle wrapper [skip ci]"
          git push
        fi
